name: Python
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 检查分支
        uses: actions/checkout@v4

      - name: 安装 Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.4

      - name: 安装模块
        run: |
          pip install requests
          pip install urllib3

      - name: 生成json文件
        run: |
          export TZ='Asia/Shanghai'
          python autoUrl.py

      - name: 暂存提交
        run: |
          git config --global user.name ${{ secrets.GIT_USER_NAME }}
          git config --global user.email ${{ secrets.GIT_USER_EMAIL }}
          git add .
          git commit -m "update" -a || echo "No changes to commit."

      - name: 拉取远程变更以避免冲突
        run: git pull --rebase

      - name: 推送到GitHub
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.MY_GITHUB_TOKEN }}
          branch: ${{ github.ref }}

      - name: 推送到Gitee
        env:
          GITEE_TOKEN: ${{ secrets.GITEE_TOKEN }}
        run: |
          git remote add gitee https://gitee.com/MINGERTAI/tvbox-json-autoupdate.git || echo "gitee remote already exists."
          git push https://$GITEE_TOKEN@gitee.com/MINGERTAI/tvbox-json-autoupdate.git HEAD:master --force
